apiVersion: v1
kind: Pod
metadata:
  name: jenkins.sagar.com
  labels:
    app: sagar-jenkins-app
  namespace: sagar-jenkins-ns
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts-alpine
      ports:
        - containerPort: 8080
